# Generated by Django 3.1.5 on 2021-01-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
